# Evaluation of pair trading

In [17]:
import importlib
import S3_Pairs_trading

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

S3_Pairs_trading = importlib.reload(S3_Pairs_trading)

In [18]:
def evaluate(String_array):
    rows = []
    for left, right in String_array:
        revenue_analysis, trades_analysis, revenue_trading, trades_trading = S3_Pairs_trading.main(left, right)
        rows.append((left, right, revenue_analysis, revenue_trading))

        revenue_analysis, trades_analysis, revenue_trading, trades_trading = S3_Pairs_trading.main( right, left)
        rows.append((right, left, revenue_analysis, revenue_trading))
    df = pd.DataFrame(
        rows,
        columns=["left", "right", "revenue analysis", "revenue test"]
    )
    return(df)

# Pairs Trading NVDA
Here we perform the pairs trading with NVIDA since it had the highest Correlation

In [19]:
#[['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']]

results_NVDA=evaluate([['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']])
display(results_NVDA)

print('average revenue analysis: ',float(results_NVDA['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_NVDA['revenue test'].sum())/10)


corr=results_NVDA.loc[:,['revenue analysis','revenue test']].corr()

print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0  NVDA  AVGO         27.318305     31.273553
1  AVGO  NVDA         22.557843     32.615204
2  NVDA  MPWR        -33.942985     78.133520
3  MPWR  NVDA        -87.520012     83.370330
4  LRCX  NVDA       -104.858637    -35.878863
5  NVDA  LRCX        -23.389433    -48.758632
6  KLAC  NVDA       -115.566710     11.571795
7  NVDA  KLAC         34.993116     -8.554175
8  MRVL  NVDA        -38.655470     32.825562
9  NVDA  MRVL         25.293469     44.598357

average revenue analysis:  -29.377051470035916
average revenue test:  22.119665074885887
Correlation analysis & test: 0.056053984068461946

# Pairs trading highest correlation

In [20]:

#[['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']]

results_corr=evaluate([['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']])
display(results_corr)

print('average revenue analysis: ',float(results_corr['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_corr['revenue test'].sum())/10)
corr=results_corr.loc[:,['revenue analysis','revenue test']].corr()
print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0  LRCX  KLAC         11.900969    -24.158273
1  KLAC  LRCX         11.496373    -22.003741
2  LRCX  AMAT          2.834292    -43.706956
3  AMAT  LRCX          4.350617    -46.334747
4  KLAC  AMAT         18.529950    -38.247084
5  AMAT  KLAC         22.044643    -32.361882
6  MCHP  NXPI         -6.397028      3.118897
7  NXPI  MCHP          6.176904      4.911169
8  MCHP   ADI        -17.349688    -19.116417
9   ADI  MCHP        -25.033045     -9.116692

average revenue analysis:  2.855398677009691
average revenue test:  -22.701572559619102
Correlation analysis & test: -0.4333504881082406