# Evaluation of pair trading

In [12]:
import importlib
import S3_Pairs_trading

import pandas as pd

S3_Pairs_trading = importlib.reload(S3_Pairs_trading)

In [13]:
def evaluate(String_array):
    rows = []
    for left, right in String_array:
        revenue_analysis, trades_analysis, revenue_test, trades_test = S3_Pairs_trading.main(left, right)
        rows.append((left, right, revenue_analysis, revenue_test))

        revenue_analysis, trades_analysis, revenue_test, trades_test = S3_Pairs_trading.main( right, left)
        rows.append((right, left, revenue_analysis, revenue_test))
    df = pd.DataFrame(
        rows,
        columns=["left", "right", "revenue analysis", "revenue test"]
    )
    return(df)

# Pairs trading suggested by Cointegration in the Dick Fuller test

In [14]:
#[['MU','MPWR'], ['MU','KLAC'],['QRVO,'MCHP],['TXN','ADI'],['TER','TXN']]

results_coint=evaluate([['MU','MPWR'], ['MU','KLAC'],['QRVO','MCHP'],['TXN','ADI'],['TER','TXN']])
display(results_coint)

print('average revenue analysis: ',float(results_coint['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_coint['revenue test'].sum())/10)
corr=results_coint.loc[:,['revenue analysis','revenue test']].corr()
print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0    MU  MPWR         -8.901584    -52.137808
1  MPWR    MU         -8.147122    -53.953368
2    MU  KLAC         69.776341   -105.148584
3  KLAC    MU         76.908454    -97.739134
4  QRVO  MCHP         76.029353     13.480345
5  MCHP  QRVO         70.117307      5.335256
6   TXN   ADI         50.150091      3.331262
7   ADI   TXN         58.654457      1.692608
8   TER   TXN         50.157805   -164.154943
9   TXN   TER         52.654761   -208.239815

average revenue analysis:  48.739986257146164
average revenue test:  -65.75341816512625
Correlation analysis & test: 0.025573209904402528

# Pairs trading highest correlation

In [15]:
#[['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']]

results_corr=evaluate([['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']])
display(results_corr)

print('average revenue analysis: ',float(results_corr['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_corr['revenue test'].sum())/10)
corr=results_corr.loc[:,['revenue analysis','revenue test']].corr()
print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0  LRCX  KLAC         11.900986    -24.158334
1  KLAC  LRCX         11.496426    -22.003752
2  LRCX  AMAT          2.834258    -43.706881
3  AMAT  LRCX          4.350693    -46.334764
4  KLAC  AMAT         18.529756    -38.247055
5  AMAT  KLAC         22.044507    -32.361854
6  MCHP  NXPI         -6.397088      3.118889
7  NXPI  MCHP          6.176873      4.911134
8  MCHP   ADI        -17.349608    -19.116375
9   ADI  MCHP        -25.032981     -9.116681

average revenue analysis:  2.8553822101712583
average revenue test:  -22.7015673652992
Correlation analysis & test: -0.4333520911757691

# Pairs Trading NVDA
Here we perform the pairs trading with NVIDA since it had the highest Correlation

In [16]:
#[['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']]

results_NVDA=evaluate([['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']])
display(results_NVDA)

print('average revenue analysis: ',float(results_NVDA['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_NVDA['revenue test'].sum())/10)


corr=results_NVDA.loc[:,['revenue analysis','revenue test']].corr()

print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0  NVDA  AVGO         27.318382     31.273458
1  AVGO  NVDA         22.557915     32.615104
2  NVDA  MPWR        -33.942989     78.133520
3  MPWR  NVDA        -87.519997     83.370346
4  LRCX  NVDA       -104.858463    -35.878826
5  NVDA  LRCX        -23.389467    -48.758625
6  KLAC  NVDA       -115.566675     11.571781
7  NVDA  KLAC         34.993086     -8.554151
8  MRVL  NVDA        -38.655419     32.825585
9  NVDA  MRVL         25.293503     44.598404

average revenue analysis:  -29.377012425280846
average revenue test:  22.119659630496386
Correlation analysis & test: 0.05605343597211613